name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Install dependencies
          run: npm install
        - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
              browser: chrome
              headed: true
              record: true
