name: Chrome headed
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5.0.9
        with:
          browser: edge
          headed: true
