name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Install dependencies
          run: npm install
        - name: Chrome headed
          uses: ./
          with:
            working-directory: examples/v9/chrome
            browser: chrome
            headed: true

        - uses: actions/upload-artifact@v3
          with:
            name: screenshots-in-headed-chrome-v9
            path: examples/v9/chrome/cypress/screenshots

        - uses: actions/upload-artifact@v3
          with:
            name: video-in-headed-chrome-v9
            path: examples/v9/chrome/cypress/videos

        - run: npx image-size cypress/screenshots/**/*.png
          working-directory: examples/v9/chrome

