name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: npm install
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
          browser: chrome
          headed: true
          record: true
