name: Chrome headed
on: 
  schedule:
  - cron: "0 10 * * *"
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version 
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5.0.9
        with:
          browser: chrome
          headed: true
